image: node:latest

stages:
  # - lint
  - typecheck
  - test
  - build
  # - comment
  # - version
  - publish

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .pnpm-store
  policy: pull-push

before_script:
  - corepack enable
  - corepack prepare --activate
  - pnpm config set store-dir .pnpm-store
  - pnpm config set @scope:registry https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
  - pnpm config set -- //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken ${CI_JOB_TOKEN}
  - pnpm install --frozen-lockfile

typecheck:
  stage: typecheck
  script:
    - pnpm typecheck

test:
  stage: test
  script:
    # - pnpm install --frozen-lockfile
    - pnpm test

build:
  stage: build
  script:
    # - pnpm install --frozen-lockfile
    - pnpm run build
  artifacts:
    paths:
      - dist/

# changesets_comment: 
#   stage: comment
#   script: 
#   # this runs the command that will detect if there are any changesets and then comment on the current Merge Request
#     - pnpm changesets-gitlab comment
#   variables: 
#     - GITLAB_TOKEN: ${$YOUR_TOKEN_HERE}
#   rules: 
#     if: $IS_MERGE_REQUEST


# publish: 
#   stage: publish
#   script: 
#     - |
#       cat <<EOF > "$HOME/.npmrc"
#       //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}
#       EOF
#     - pnpm build
#     - pnpm changesets-gitlab
#   variables:
#     GITLAB_TOKEN: $YOUR_TOKEN_HERE
#     NPM_TOKEN: $CI_JOB_TOKEN
#     INPUT_PUBLISH: pnpm changeset publish
#   rules: 
#     - if: $IS_MAIN_BRANCH

# version:
#   stage: version
#   script:
#     - git config user.name "GitLab CI"
#     - git config user.email "rtorcato@me.com"
#     - pnpm changeset version
#     - git add .
#     - git commit -m "Version packages [skip ci]"
#     - git push origin HEAD:$CI_COMMIT_REF_NAME
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# publish:
#   stage: publish
#   script:
#     - echo "@your-scope:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
#     - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
#     - pnpm changeset publish
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# publish:
#   stage: publish
#   script:
#     - echo "@your-gitlab-username:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
#     - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
#     - npm publish

#   only:
#     - tags


# publish-npm:
#   stage: deploy
#   script:
#     - echo "@scope:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
#     - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
#     - npm publish


publish:
  stage: publish
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  environment: production