import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Autogenerated from the docs/ tree for now. As Components (#8) and the
// TypeDoc API reference (#9) land, replace this with explicit categories.
const sidebars: SidebarsConfig = {
	docs: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
